# Generated by Django 5.1.7 on 2025-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0002_remove_managerprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='username',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
