# Generated by Django 5.1.7 on 2025-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0004_customer_raw_password_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
