# Generated by Django 5.1.7 on 2025-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0005_alter_customer_address_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='can_cashout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_card_cvc',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
