# Generated by Django 5.1.7 on 2025-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0006_customer_can_cashout_customer_credit_card_cvc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('coingecko_id', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('value_usd', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
