# Generated by Django 5.1.7 on 2025-05-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0008_cryptotransfer_userwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('fee', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custLogin.customer')),
                ('from_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='custLogin.cryptocurrency')),
                ('to_crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='custLogin.cryptocurrency')),
            ],
        ),
    ]
