# Generated by Django 5.1.7 on 2025-05-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custLogin', '0009_cryptoconvert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
